BookstoreApp/Models/ViewModels/OrderSearchResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookstoreApp.Models.ViewModels
{
    public class OrderSearchResultViewModel
    {
        public string orderId { get; set; }
        public string storeName { get; set; }
        public string bookName { get; set; }

        public OrderSearchResultViewModel(string ordId, string stName, string bkName)
        {
            orderId = ordId;
            storeName = stName;
            bookName = bkName;
        }
    }
}

BookstoreApp/Models/sale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public string stor_id { get; set; }
        public string ord_num { get; set; }
        public System.DateTime ord_date { get; set; }
        public short qty { get; set; }
        public string payterms { get; set; }
        public string title_id { get; set; }
    
        public virtual store store { get; set; }
        public virtual title title { get; set; }
    }
}

BookstoreApp/Controllers/salesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookstoreApp.Models;
using BookstoreApp.Models.ViewModels;

namespace BookstoreApp.Controllers
{
    public class salesController : Controller
    {
        private pubsEntities db = new pubsEntities();

        // GET: sales
        public ActionResult Index()
        {
            var sales = db.sales.Include(s => s.store).Include(s => s.title);
            return View(sales.ToList());
        }

        // GET: sales
        public ActionResult OrderSearch()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult OrderSearch([Bind(Include = "nameFrom,nameTo,dateFrom,dateTo")] OrderSearchFormViewModel searchFormData)
        {
            var nameFrom = searchFormData.nameFrom;
            var nameTo = searchFormData.nameTo;
            var dateFrom = searchFormData.dateFrom;
            var dateTo = searchFormData.dateTo;

            var orders = from order in db.sales
                         from book in db.titles
                         from store in db.stores
                         where order.ord_date > dateFrom
                         where order.ord_date < dateTo
                         where book.title_id == order.title_id
                         where store.stor_id == order.stor_id
                         //where store.stor_name[0] > nameFrom
                         //where store.stor_name[0] < nameTo
                         select new
                         {
                             orderId = order.ord_num,
                             storeName = store.stor_name,
                             bookName = book.title1
                         };

            List<OrderSearchResultViewModel> results = new List<OrderSearchResultViewModel>();
            foreach (var ord in orders)
            {
                results.Add(new OrderSearchResultViewModel(ord.orderId, ord.storeName, ord.bookName));
            }

            return View("OrderSearchResult",results);


            //var books = (from book in db.titles
            //             where book.pubdate > dateFrom
            //             where book.pubdate < dateTo
            //             orderby book.ytd_sales descending
            //             select book)
            //               .Take(searchFormData.sales);

            //var authors = (from b in books
            //               from author in db.authors
            //               from tauth in db.titleauthors
            //               where tauth.title_id == b.title_id
            //               where tauth.au_id == author.au_id
            //               select author).ToList();

            //return View("Result", authors);
        }

        // GET: sales/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // GET: sales/Create
        public ActionResult Create()
        {
            ViewBag.stor_id = new SelectList(db.stores, "stor_id", "stor_name");
            ViewBag.title_id = new SelectList(db.titles, "title_id", "title1");
            return View();
        }

        // POST: sales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "stor_id,ord_num,ord_date,qty,payterms,title_id")] sale sale)
        {
            if (ModelState.IsValid)
            {
                db.sales.Add(sale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.stor_id = new SelectList(db.stores, "stor_id", "stor_name", sale.stor_id);
            ViewBag.title_id = new SelectList(db.titles, "title_id", "title1", sale.title_id);
            return View(sale);
        }

        // GET: sales/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            ViewBag.stor_id = new SelectList(db.stores, "stor_id", "stor_name", sale.stor_id);
            ViewBag.title_id = new SelectList(db.titles, "title_id", "title1", sale.title_id);
            return View(sale);
        }

        // POST: sales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "stor_id,ord_num,ord_date,qty,payterms,title_id")] sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.stor_id = new SelectList(db.stores, "stor_id", "stor_name", sale.stor_id);
            ViewBag.title_id = new SelectList(db.titles, "title_id", "title1", sale.title_id);
            return View(sale);
        }

        // GET: sales/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            sale sale = db.sales.Find(id);
            db.sales.Remove(sale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookstoreApp/Views/sales/Create.cshtml
@model BookstoreApp.Models.sale

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.stor_id, "stor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("stor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.stor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ord_num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ord_num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ord_num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ord_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ord_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ord_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.payterms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.payterms, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.payterms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title_id, "title_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("title_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.title_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookstoreApp/Views/sales/Delete.cshtml
@model BookstoreApp.Models.sale

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>sale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ord_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ord_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.payterms)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.payterms)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.store.stor_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.store.stor_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title.title1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title.title1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookstoreApp/Views/sales/Details.cshtml
@model BookstoreApp.Models.sale

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>sale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ord_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ord_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.payterms)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.payterms)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.store.stor_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.store.stor_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title.title1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title.title1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BookstoreApp/Views/sales/Edit.cshtml
@model BookstoreApp.Models.sale

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.stor_id)

        @Html.HiddenFor(model => model.ord_num)

        <div class="form-group">
            @Html.LabelFor(model => model.ord_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ord_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ord_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.payterms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.payterms, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.payterms, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.title_id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookstoreApp/Views/sales/Index.cshtml
@model IEnumerable<BookstoreApp.Models.sale>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ord_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.qty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.payterms)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.store.stor_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title.title1)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ord_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.qty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.payterms)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.store.stor_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title.title1)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

BookstoreApp/Views/sales/OrderSearch.cshtml
@model BookstoreApp.Models.ViewModels.OrderSearchFormViewModel

@{
    ViewBag.Title = "OrderSearch";
}

<h2>Search for specific orders</h2>

<form action="@Url.Action("OrderSearch","sales")" method="post">

    <label for="nameFrom">Enter starting range of store name</label>  <br />
    <input id="nameFrom" name="nameFrom" type="text" /><br /><br />
    <label for="nameTo">Enter ending range of store name</label>  <br />
    <input id="nameTo" name="nameTo" type="text" /><br /><br />
    <label for="dateFrom">Enter starting range of when order was made</label>  <br />
    <input id="dateFrom" name="dateFrom" type="date" value="1980-01-01" /><br /><br />
    <label for="dateTo">Enter starting range of when order was made</label>  <br />
    <input id="dateTo" name="dateTo" type="date" />
    <br /><br />
    <input type="submit" value="Search" />
</form>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookstoreApp/Views/sales/OrderSearchResult.cshtml
@model IEnumerable<BookstoreApp.Models.ViewModels.OrderSearchResultViewModel>

@{
    ViewBag.Title = "OrderSearchResult";
}

<h2>OrderSearchResult</h2>


<table class="table">
    <tr>
        <th>
            Order ID
        </th>
        <th>
            Store Name
        </th>
        <th>
            Book Name
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.orderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.storeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bookName)
            </td>

        </tr>
    }

</table>